### ISSUE TITLE
encoding of '`' and '"' in query parameters

### ISSUE THREAD

**Issue by faisalferoz** [damnhandy/Handy-URI-Templates#22]
as per the [unreserved](http://tools.ietf.org/html/rfc3986#section-2.3) characters, back-tick `` ` `` and inverted quote `"` both don't fall into the unreserved set but these are not encoded when using UriTemplate.

**Comment by dantheperson** [comment]
Any plans to release this fix?  I presume it would also work in path variables.  I would expect in this example that the backtick is %60 encoded and thus parse as a URI, just as the greaterThan example is.


    @Test
    public void testBacktick() throws URISyntaxException {
        String url = UriTemplate.fromTemplate("http://example.com/{var}").set("var", "`").expand();
        URI uri = new URI(url);
    }

    @Test
    public void testGreaterThan() throws URISyntaxException {
        String url = UriTemplate.fromTemplate("http://example.com/{var}").set("var", ">").expand();
        URI uri = new URI(url);
    }

**Comment by dantheperson** [comment]
I have tested with 2.0.3-SNAPSHOT and it still issue is still there.
