### ISSUE TITLE
Expanding enums

### ISSUE THREAD

**Issue by vicmosin** [damnhandy/Handy-URI-Templates#35]
Why forbid to pass enums??

https://github.com/damnhandy/Handy-URI-Templates/blob/master/src/main/java/com/damnhandy/uri/template/DefaultVarExploder.java#L120

**Comment by damnhandy** [comment]
Enums wouldn't be captured there, but here:

https://github.com/damnhandy/Handy-URI-Templates/blob/master/src/main/java/com/damnhandy/uri/template/UriTemplate.java#L609

The `DefaultVarExploder` should only be called when the type is not a primitive, CharSequence, Number, or Date type. I haven't tested enums, but there probably needs to be some thought into how they are handled.

**Comment by vicmosin** [comment]
So they are not)) it fails with `The value must an object` exception

**Comment by damnhandy** [comment]
Clearly not tested :) I'll have a gander at this over the weekend.

**Comment by damnhandy** [comment]
@vicmosin I'm really surprised that such an obvious bug took 4 years for someone to find it. Thanks for the report. A few minor tweaks and it's functional now. I've pushed a snapshot to Maven Central under version `2.1.0-SNAPSHOT` Should have a release out by the end of the weekend.

**Comment by vicmosin** [comment]
Confirmed, `2.1.0-SNAPSHOT` fixes the issue.
What about 2.0.5-SNAPSHOT described in docs? When release version is expected to be?

**Comment by damnhandy** [comment]
I'm going straight to 2.1. Should be posting that later today.
